# Generated by Django 4.2.6 on 2024-01-11 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='Phn',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator('[6-9]\\d{9}')]),
        ),
    ]
